// @ts-nocheck
// This file is automatically generated by Firebase Studio.
// Do not edit this file.

// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: 'AIzaSyAuFFwv1_KF2x5iHJpx1a4y93JP5wfeorc',
  authDomain: 'studio-9278190762-b26f2.firebaseapp.com',
  projectId: 'studio-9278190762-b26f2',
  appId: '1:977396460140:web:2b05b31795d202cdd50649',
};
